version: '3'

tasks:
  build:
    cmds:
      - go build -o fiberApp cmd/server/main.go

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - docker-compose up --build

  integration-test:
    cmds:
      - docker-compose up -d postgres
      - go test -tags=integration -v ./...
    env:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      DB_DB: "postgres"
      DB_HOST: "0.0.0.0"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      SSL_MODE: "disable"
      SIGNING_KEY: TOKE_SIGNING_KEY

  acceptance-test:
    cmds:
      - docker-compose up -d --build
      - go test -tags=e2e -v ./...